services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: examin-backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - examin-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: examin-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - examin-network

networks:
  examin-network:
    driver: bridge
